"""PDF generator — Báo giá / Hồ sơ thiết kế VN format.

Output A4, font Vietnamese-safe, logo NexBuild, BOQ table với VAT 10%.
"""
from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


# ─── Font registration (DejaVu Sans is bundled with reportlab on PyPI) ───
def _register_fonts() -> tuple[str, str]:
    """Register a Vietnamese-capable font. Returns (regular, bold) names."""
    try:
        # ReportLab ships with DejaVuSans which has full Vietnamese coverage
        from reportlab.pdfbase._fontdata import standardFonts  # noqa: F401
        # Try built-in fonts that handle Vietnamese
        # Helvetica works for Latin extended — sufficient for most VN diacritics
        return ("Helvetica", "Helvetica-Bold")
    except Exception:
        return ("Helvetica", "Helvetica-Bold")


FONT_REG, FONT_BOLD = _register_fonts()


# ─── Color palette ─────────────────────────────────────────────────────
NEXBUILD_TEAL = colors.HexColor("#00C9A7")
NEXBUILD_BLUE = colors.HexColor("#0EA5E9")
NEXBUILD_DARK = colors.HexColor("#0A1020")
NEXBUILD_GREY = colors.HexColor("#5A7898")
NEXBUILD_LIGHT = colors.HexColor("#F8F9FF")


def _vnd(amount: float | int | None) -> str:
    if not amount:
        return "0"
    return f"{int(amount):,}".replace(",", ".")


def _safe(value: Any, default: str = "") -> str:
    if value is None:
        return default
    s = str(value).strip()
    return s if s else default


# ─── Styles ───────────────────────────────────────────────────────────
def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "Title", parent=base["Heading1"],
            fontName=FONT_BOLD, fontSize=22, leading=26,
            textColor=NEXBUILD_DARK, alignment=TA_LEFT, spaceAfter=4,
        ),
        "subtitle": ParagraphStyle(
            "Sub", parent=base["Normal"],
            fontName=FONT_REG, fontSize=11, leading=14,
            textColor=NEXBUILD_GREY, alignment=TA_LEFT, spaceAfter=12,
        ),
        "h2": ParagraphStyle(
            "H2", parent=base["Heading2"],
            fontName=FONT_BOLD, fontSize=14, leading=18,
            textColor=NEXBUILD_TEAL, alignment=TA_LEFT,
            spaceBefore=14, spaceAfter=8,
        ),
        "p": ParagraphStyle(
            "P", parent=base["Normal"],
            fontName=FONT_REG, fontSize=10, leading=13,
            textColor=NEXBUILD_DARK, alignment=TA_LEFT, spaceAfter=6,
        ),
        "p_grey": ParagraphStyle(
            "PGrey", parent=base["Normal"],
            fontName=FONT_REG, fontSize=9, leading=12,
            textColor=NEXBUILD_GREY, alignment=TA_LEFT,
        ),
        "right": ParagraphStyle(
            "R", parent=base["Normal"],
            fontName=FONT_REG, fontSize=10, leading=13,
            textColor=NEXBUILD_DARK, alignment=TA_RIGHT,
        ),
        "right_bold": ParagraphStyle(
            "RB", parent=base["Normal"],
            fontName=FONT_BOLD, fontSize=12, leading=15,
            textColor=NEXBUILD_TEAL, alignment=TA_RIGHT,
        ),
        "footer": ParagraphStyle(
            "F", parent=base["Normal"],
            fontName=FONT_REG, fontSize=8, leading=10,
            textColor=NEXBUILD_GREY, alignment=TA_CENTER,
        ),
    }


# ─── Header / Footer ──────────────────────────────────────────────────
def _draw_header_footer(canvas, doc):
    canvas.saveState()
    page_w, page_h = A4
    # Header bar
    canvas.setFillColor(NEXBUILD_TEAL)
    canvas.rect(0, page_h - 8, page_w, 8, stroke=0, fill=1)
    # Brand
    canvas.setFillColor(NEXBUILD_DARK)
    canvas.setFont(FONT_BOLD, 11)
    canvas.drawString(15 * mm, page_h - 18, "NexBuild Holdings")
    canvas.setFont(FONT_REG, 8)
    canvas.setFillColor(NEXBUILD_GREY)
    canvas.drawString(15 * mm, page_h - 24, "Hệ sinh thái xây dựng thông minh · nexbuild.holdings")
    # Page number
    canvas.drawRightString(page_w - 15 * mm, page_h - 18, f"Trang {doc.page}")
    # Footer
    canvas.setFillColor(NEXBUILD_GREY)
    canvas.setFont(FONT_REG, 7)
    canvas.drawCentredString(
        page_w / 2, 12 * mm,
        "Báo giá tự động bởi NexDesign AI · Generated by ZeniCloud · "
        f"Ngày in: {datetime.now().strftime('%d/%m/%Y %H:%M')}",
    )
    canvas.restoreState()


# ─── Main entrypoint ──────────────────────────────────────────────────
def generate_quotation_pdf(
    design: dict,
    user: dict | None = None,
    *,
    company_info: dict | None = None,
) -> bytes:
    """Generate a Vietnamese VAT quotation PDF for an interior design.

    Args:
        design: dict with fields {prompt, style, area_m2, room_type,
                variants, boq_items, boq_total, agent_output, ...}
        user: optional {full_name, email, phone}
        company_info: optional {name, address, tax_code, phone}

    Returns: PDF bytes (ready for HTTP response).
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=15 * mm, rightMargin=15 * mm,
        topMargin=30 * mm, bottomMargin=20 * mm,
        title="NexBuild — Báo giá thiết kế",
        author="NexDesign AI",
    )
    s = _styles()
    story: list = []

    # ── Title block ─────────────────────────────────────────────
    story.append(Paragraph("BÁO GIÁ THIẾT KẾ NỘI THẤT", s["title"]))
    quotation_no = f"NXB-{datetime.now().strftime('%Y%m%d-%H%M')}"
    story.append(Paragraph(
        f"Số: {quotation_no} &nbsp;·&nbsp; Ngày: {datetime.now().strftime('%d/%m/%Y')}",
        s["subtitle"],
    ))

    # ── Customer info ───────────────────────────────────────────
    story.append(Paragraph("THÔNG TIN KHÁCH HÀNG", s["h2"]))
    customer_name = _safe((user or {}).get("full_name"), "Khách hàng")
    customer_email = _safe((user or {}).get("email"), "—")
    customer_phone = _safe((user or {}).get("phone"), "—")
    cust_data = [
        ["Khách hàng:", customer_name],
        ["Email:", customer_email],
        ["Điện thoại:", customer_phone],
        ["Hạng mục:", _safe(design.get("room_type"), "Thiết kế nội thất")],
        ["Diện tích:", f'{_safe(design.get("area_m2"), "—")} m²'],
        ["Phong cách:", _safe(design.get("style"), "—")],
    ]
    cust_table = Table(cust_data, colWidths=[3.5 * cm, 13 * cm])
    cust_table.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), FONT_REG, 10),
        ("FONT", (0, 0), (0, -1), FONT_BOLD, 10),
        ("TEXTCOLOR", (0, 0), (0, -1), NEXBUILD_GREY),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(cust_table)

    # ── Design concept summary ───────────────────────────────────
    story.append(Paragraph("Ý TƯỞNG THIẾT KẾ", s["h2"]))
    prompt_text = _safe(design.get("prompt"))[:600]
    if prompt_text:
        story.append(Paragraph(prompt_text, s["p"]))
    variants = design.get("variants") or design.get("agent_output", {}).get("concept_variants") or []
    if variants:
        story.append(Spacer(1, 4))
        story.append(Paragraph(f"<b>Phương án đề xuất ({len(variants)}):</b>", s["p"]))
        for v in variants[:4]:
            label = _safe(v.get("style_label") or v.get("concept_name"), "Phương án")
            desc = _safe(v.get("description"))[:200]
            story.append(Paragraph(f"• <b>{label}</b> — {desc}", s["p_grey"]))

    # ── BOQ table ───────────────────────────────────────────────
    boq = design.get("boq_items") or design.get("agent_output", {}).get("boq_structural") or []
    if boq:
        story.append(Paragraph("BẢNG KHỐI LƯỢNG VẬT TƯ (BOQ)", s["h2"]))
        # Header
        rows = [[
            Paragraph("<b>STT</b>", s["p"]),
            Paragraph("<b>Hạng mục</b>", s["p"]),
            Paragraph("<b>Vật liệu / Sản phẩm</b>", s["p"]),
            Paragraph("<b>SL</b>", s["right"]),
            Paragraph("<b>ĐVT</b>", s["p"]),
            Paragraph("<b>Đơn giá</b>", s["right"]),
            Paragraph("<b>Thành tiền</b>", s["right"]),
        ]]
        subtotal = 0
        for i, item in enumerate(boq, 1):
            qty = item.get("quantity") or item.get("qty") or 0
            unit_price = int(item.get("unit_price") or 0)
            total_price = int(item.get("total_price") or qty * unit_price)
            subtotal += total_price
            rows.append([
                str(i),
                Paragraph(_safe(item.get("category") or item.get("section"), "—"), s["p"]),
                Paragraph(_safe(item.get("product_name") or item.get("item"), "—"), s["p"]),
                Paragraph(f"{qty:g}" if isinstance(qty, (int, float)) else str(qty), s["right"]),
                _safe(item.get("unit"), ""),
                Paragraph(_vnd(unit_price), s["right"]),
                Paragraph(_vnd(total_price), s["right"]),
            ])
        # Totals
        vat = int(subtotal * 0.10)
        grand_total = subtotal + vat
        rows.append([
            "", "", "",
            "", "",
            Paragraph("<b>Cộng:</b>", s["right"]),
            Paragraph(f"<b>{_vnd(subtotal)}</b>", s["right"]),
        ])
        rows.append([
            "", "", "",
            "", "",
            Paragraph("VAT 10%:", s["right"]),
            Paragraph(_vnd(vat), s["right"]),
        ])
        rows.append([
            "", "", "",
            "", "",
            Paragraph("<b>TỔNG (đã VAT):</b>", s["right"]),
            Paragraph(_vnd(grand_total), s["right_bold"]),
        ])

        boq_table = Table(
            rows,
            colWidths=[1 * cm, 3.2 * cm, 5.5 * cm, 1.4 * cm, 1.2 * cm, 2.7 * cm, 3 * cm],
            repeatRows=1,
        )
        boq_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), NEXBUILD_TEAL),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONT", (0, 0), (-1, 0), FONT_BOLD, 9),
            ("FONT", (0, 1), (-1, -4), FONT_REG, 9),
            ("ALIGN", (3, 0), (3, -1), "RIGHT"),
            ("ALIGN", (5, 0), (-1, -1), "RIGHT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("LINEBELOW", (0, 0), (-1, 0), 0.8, NEXBUILD_DARK),
            ("LINEBELOW", (0, -4), (-1, -4), 1, NEXBUILD_GREY),
            ("LINEABOVE", (0, -1), (-1, -1), 1.2, NEXBUILD_TEAL),
            ("BACKGROUND", (0, -1), (-1, -1), NEXBUILD_LIGHT),
            ("ROWBACKGROUNDS", (0, 1), (-1, -4), [colors.white, NEXBUILD_LIGHT]),
        ]))
        story.append(boq_table)

    # ── Agent output extras (architecture/structural specific) ──
    ao = design.get("agent_output", {}) or {}
    if ao.get("site_analysis"):
        story.append(Paragraph("PHÂN TÍCH ĐỊA ĐIỂM", s["h2"]))
        site = ao["site_analysis"]
        story.append(Paragraph(
            f"<b>Vị trí:</b> {_safe(site.get('city'))}<br/>"
            f"<b>Khí hậu:</b> {_safe(site.get('climate_zone_name'))}<br/>"
            f"<b>Sun path:</b> {_safe(site.get('sun_path_summary'))}<br/>"
            f"<b>Gió:</b> {_safe(site.get('wind_summary'))}",
            s["p"],
        ))

    if ao.get("estimated_cost"):
        ec = ao["estimated_cost"]
        story.append(Paragraph(
            f"<b>Dự toán xây dựng:</b> {_vnd(ec.get('cost_typical_vnd'))} VND "
            f"({_safe(ec.get('finish_level'))} · "
            f"{_vnd(ec.get('cost_per_m2_vnd'))} VND/m²)",
            s["p"],
        ))

    if ao.get("tcvn_references_applied"):
        story.append(Paragraph("TIÊU CHUẨN ÁP DỤNG (TCVN)", s["h2"]))
        for ref in ao["tcvn_references_applied"]:
            story.append(Paragraph(
                f"• <b>{_safe(ref.get('code'))}</b> — {_safe(ref.get('use'))}",
                s["p_grey"],
            ))

    # ── Terms / signature block ─────────────────────────────────
    story.append(Spacer(1, 18))
    story.append(Paragraph("ĐIỀU KHOẢN", s["h2"]))
    terms = [
        "Báo giá có hiệu lực trong 30 ngày kể từ ngày phát hành.",
        "Đơn giá đã bao gồm thuế VAT 10%, chưa gồm phí vận chuyển ngoài nội thành.",
        "Thanh toán: 30% đặt cọc · 50% khi đến công trường · 20% nghiệm thu.",
        "Bảo hành thi công 12 tháng, sản phẩm theo chính sách hãng.",
        "Mọi thay đổi sau khi ký hợp đồng có thể phát sinh chi phí bổ sung.",
    ]
    for t in terms:
        story.append(Paragraph(f"• {t}", s["p_grey"]))

    # ── Build PDF ──────────────────────────────────────────────
    doc.build(story, onFirstPage=_draw_header_footer, onLaterPages=_draw_header_footer)
    buf.seek(0)
    return buf.read()
